services:
  - type: web
    name: app-transcricao
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
